server:
  port: 5555

management:
  endpoints:
    web:
      exposure:
        include: "*"

spring:
  main:
    web-application-type: reactive
  application:
    name: api-gateway

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

#  cloud:
#    gateway:
#      routes:
#        - id: service1
#          uri: lb://SERVICE1
#          predicates:
#            - Path=/user/**
#          filters:
#            - UserServiceFilter
#        - id: business-service
#          uri: lb://BUSINESS-SERVICE
#          predicates:
#            - Path=/business/**
#      default-filters:
#        - name: LogFilter # ?? ????? ??? ?
#          args:
#            message: Hello LogFilter
